processor:
  build: ../data-processor/
  links:
    - rabbitmq
    - db
  environment:
    VIP_DP_AWS_ACCESS_KEY:
    VIP_DP_AWS_SECRET_KEY:
    VIP_DP_S3_BUCKET:
    VIP_DP_SQS_REGION:
    VIP_DP_SQS_QUEUE:
    VIP_DP_SQS_FAIL_QUEUE:
    VIP_DP_RABBITMQ_EXCHANGE:
rabbitmq:
  image: rabbitmq:3.5.3-management
  ports:
    - "15672"
  hostname: qa-engine-rabbit
db:
  image: postgres:9.4.1
  ports:
    - "5432"
  environment:
    POSTGRES_USER:
    POSTGRES_PASSWORD:
    POSTGRES_DATABASE:
metis:
  build: ../Metis/
  environment:
    VIP_DP_RABBITMQ_EXCHANGE:
  links:
    - db
    - processor
    - rabbitmq
  ports:
    - 4000:4000
